In [26]:
import numpy as np
arr = np.array([[[1,2,3,4],[2,3,4,5]],[[4,4,5,6],[4,7,8,7]]])
print(arr,type(arr))
print("\ndimension of the array: ",arr.ndim)
print(arr[0,1,2])

[[[1 2 3 4]
  [2 3 4 5]]

 [[4 4 5 6]
  [4 7 8 7]]] <class 'numpy.ndarray'>

dimension of the array:  3
4


In [41]:
ar = np.array([2,3,4,5],dtype='i')
print(ar)

[2 3 4 5]


In [24]:
b = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(b[1,1])

3


In [44]:
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1[4:])

[5 6 7]


In [46]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.ndim)
print(arr2[1,0:])

2
[ 6  7  8  9 10]


In [60]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x = arr3.copy()
arr3[0] = 42
print(arr3)
print(x)
print(arr3.shape)

[[42 42 42 42 42]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [61]:
#reshape array

arr4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr4.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
#iterating array

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for y in i:
        print(y)

1
2
3
4
5
6


In [70]:
#concatinating array

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
for x in n:
    print(x)

1
2
3
4
5
6
